name: CD - Deploy Backend Services to AKS

on:
  workflow_dispatch:

env:
  RESOURCE_GROUP: sit722-week08
  CLUSTER_NAME: sit722aks013
  ACR_LOGIN_SERVER: sit722acr013.azurecr.io
  NAMESPACE: default

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS Context
        uses: azure/aks-set-context@v4
        with:
          resource-group: sit722-week08
          cluster-name: sit722aks013

      - name: Create namespace if not exists
        run: |
          kubectl get ns ${{ env.NAMESPACE }} || kubectl create ns ${{ env.NAMESPACE }}

      - name: Deploy Backend Services
        run: |
          kubectl apply -f k8s/configmaps.yaml -n ${{ env.NAMESPACE }}
          kubectl apply -f k8s/secrets.yaml -n ${{ env.NAMESPACE }}
          kubectl apply -f k8s/product-db.yaml -n ${{ env.NAMESPACE }}
          kubectl apply -f k8s/product-service.yaml -n ${{ env.NAMESPACE }}
          kubectl apply -f k8s/order-db.yaml -n ${{ env.NAMESPACE }}
          kubectl apply -f k8s/order-service.yaml -n ${{ env.NAMESPACE }}

      - name: Wait for External IPs
        run: |
          echo "Waiting for Product & Order external IPs..."
          kubectl get svc -n ${{ env.NAMESPACE }}
          sleep 30
          kubectl get svc -n ${{ env.NAMESPACE }}