name: CI - Consolidated Validation

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  ACR_NAME: sit722acr013
  ACR_LOGIN_SERVER: sit722acr013.azurecr.io
  IMAGE_TAG: ${{ github.sha }}-${{ github.run_id }}
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres

jobs:
  validate:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        service: [product_service, order_service, frontend]
    
    name: Validate ${{ matrix.service }}
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: ${{ matrix.service == 'product_service' && 'products' || matrix.service == 'order_service' && 'orders' || 'dummy' }}
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Backend validation
      - name: Set up Python for backend
        if: matrix.service != 'frontend'
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install backend dependencies
        if: matrix.service != 'frontend'
        run: |
          pip install --upgrade pip
          pip install -r backend/${{ matrix.service }}/requirements.txt
          pip install pytest httpx

      - name: Run backend tests
        if: matrix.service != 'frontend'
        working-directory: backend/${{ matrix.service }}
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_DB: ${{ matrix.service == 'product_service' && 'products' || 'orders' }}
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        run: pytest tests --maxfail=1 --disable-warnings -q

      # Frontend validation
      - name: Set up Node.js for frontend
        if: matrix.service == 'frontend'
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Validate frontend structure
        if: matrix.service == 'frontend'
        run: |
          echo "Validating frontend files..."
          test -f frontend/index.html || (echo "❌ index.html missing" && exit 1)
          test -f frontend/main.js || (echo "❌ main.js missing" && exit 1)
          test -f frontend/Dockerfile || (echo "❌ Dockerfile missing" && exit 1)
          echo "✅ Frontend validation passed!"

      - name: Build frontend Docker image (validation)
        if: matrix.service == 'frontend'
        run: |
          docker build -t frontend-test:${{ github.sha }} ./frontend
          echo "✅ Frontend Docker build successful!"

  # Build and push only after validation passes and only on push to main
  build_and_push:
    runs-on: ubuntu-latest
    needs: validate
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    strategy:
      matrix:
        service: [product_service, order_service, frontend]
    
    name: Build & Push ${{ matrix.service }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to ACR
        run: az acr login --name ${{ env.ACR_NAME }}

      - name: Build & Push product_service Image
        if: matrix.service == 'product_service'
        run: |
          docker build -t ${{ env.ACR_LOGIN_SERVER }}/product_service:latest \
                       -t ${{ env.ACR_LOGIN_SERVER }}/product_service:${{ env.IMAGE_TAG }} \
                       ./backend/product_service
          docker push ${{ env.ACR_LOGIN_SERVER }}/product_service:latest
          docker push ${{ env.ACR_LOGIN_SERVER }}/product_service:${{ env.IMAGE_TAG }}

      - name: Build & Push order_service Image
        if: matrix.service == 'order_service'
        run: |
          docker build -t ${{ env.ACR_LOGIN_SERVER }}/order_service:latest \
                       -t ${{ env.ACR_LOGIN_SERVER }}/order_service:${{ env.IMAGE_TAG }} \
                       ./backend/order_service
          docker push ${{ env.ACR_LOGIN_SERVER }}/order_service:latest
          docker push ${{ env.ACR_LOGIN_SERVER }}/order_service:${{ env.IMAGE_TAG }}

      - name: Build & Push frontend Image
        if: matrix.service == 'frontend'
        run: |
          docker build -t ${{ env.ACR_LOGIN_SERVER }}/frontend:latest ./frontend
          docker push ${{ env.ACR_LOGIN_SERVER }}/frontend:latest

      - name: Logout from Azure
        if: always()
        run: az logout